language: python
dist: trusty
sudo: false

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

install:
  - travis_retry pip install --upgrade pip
  - travis_retry pip install coveralls
  - travis_retry pip install flake8 tox pytest

script:
  - tox -e $(echo py$TRAVIS_PYTHON_VERSION | tr -d .)

after_success:
  - coveralls
