name: CI

on:
  push:
    branches:
    - master
  pull_request:

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "latest"
      - name: Ruff lint
        run: uv run --group lint -- ruff check

  tests:
    name: Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    needs: ["lint"]
    strategy:
      matrix:
        python-version:
        - "3.8"
        - "3.9"
        - "3.10"
        - "3.11"
        - "3.12"
        - "3.13"

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install uv
      uses: astral-sh/setup-uv@22695119d769bdb6f7032ad67b9bca0ef8c4a174 # v5
    - name: Install required Python versions
      run: |
        uv python install ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        uv sync --frozen --all-groups
    - name: Run tox targets for python ${{ matrix.python-version }}
      run: uv run tox run -f $(echo ${{ matrix.python-version }} | tr -d .)

  coverage:
    name: Coverage
    runs-on: ubuntu-22.04
    needs: tests
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: python -m pip install --upgrade coverage[toml]
#
#      - name: Combine coverage and fail if it's <95%
#        run: |
#          python -m coverage combine
#          python -m coverage html --skip-covered --skip-empty
#          python -m coverage report --fail-under=95
